services:
  # MySQL service
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./.shared:/.shared
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    networks:
      - app_network

  # PHP FPM service
  php-fpm:
    build:
      context: .
      dockerfile: ./services/php-fpm/Dockerfile
    container_name: php-fpm
    restart: unless-stopped
    working_dir: /apps
    volumes:
      - ./apps/php:/apps/php
      - ./.shared:/.shared
      - ./configs/php-fpm/php.ini:/usr/local/etc/php/php.ini
    env_file:
      - ./.env
    networks:
      - app_network

  # Nginx service
  nginx:
    build:
      context: .
      dockerfile: ./services/nginx/Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./apps:/apps
      - ./.shared:/.shared
      - ./configs/nginx:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
