services:
  # PHP service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./infra/php-fpm/php.ini-development:/usr/local/etc/php/php.ini
    networks:
      - laravel_app_network
    user: "1000:1000"

  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel_app_network

networks:
  laravel_app_network:
    driver: bridge
