services:
  # MySQL service
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app_user
    env_file:
      - ./fixtures/envs
    ports:
      - "3306:3306"
    networks:
      - app_network

  # PHP FPM service
  php-fpm:
    build:
      context: .
      dockerfile: php-fpm.dockerfile
    container_name: php-fpm
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./infra/php-fpm/php.ini-development:/usr/local/etc/php/php.ini
    env_file:
      - ./fixtures/envs
    networks:
      - app_network

  # Nginx service
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app_network


networks:
  app_network:
    driver: bridge
